---

- name: Install Docker-py for Python3.
  pip:
    name: docker-py==1.10.6

- name: Make sure the Prometheus data directory Docker Volume is present.
  docker_volume:
    name: prometheus-config
    state: present

- name: Make sure the permissions are correct for the Docker Volume.
  file:
    path: /var/lib/docker/volumes/prometheus-config/_data/
    owner: nobody
    group: nogroup

- name: Start the Prometheus Docker container and make sure it is running.
  docker_container:
    name: prometheus-server
    image: prom/prometheus
    state: started
    restart: yes
    ports:
      - "9090:9090"
    volumes:
      - "prometheus-config:/etc/prometheus:rw"
    command:
      - "--storage.tsdb.retention.time=360d"

- name: Create the Prometheus server config based on template.
  template:
    src: prometheus.yml.j2
    dest: /var/lib/docker/volumes/prometheus-config/_data/prometheus.yml

- name: Create the alerting rules template.
  copy :
    src: alerting.yml.j2
    dest: /var/lib/docker/volumes/prometheus-config/_data/alerting.yml

- name: Make sure the permissions are correct for the Docker Volume. Again, in case it changed when pulling the container.
  file:
    path: /var/lib/docker/volumes/prometheus-config/_data/
    owner: nobody
    group: nogroup
